name: pulser-env
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cycler=0.11.0
  - dill=0.3.4
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.6.3
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.3.5
  - pillow=8.4.0
  - pip=21.2.2
  - pyparsing=3.0.4
  - python=3.7.11
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2021.3
  - qutip=4.6.2
  - readline=8.1.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - backports-cached-property==1.0.1
    - cffi==1.15.0
    - cryptography==36.0.1
    - importlib-metadata==4.10.1
    - mpmath==1.2.1
    - ntlm-auth==1.5.0
    - pbr==5.8.0
    - ply==3.11
    - psutil==5.9.0
    - pulser==0.4.2
    - pycparser==2.21
    - python-constraint==1.4.0
    - qiskit==0.34.1
    - qiskit-aer==0.10.2
    - qiskit-ibmq-provider==0.18.3
    - qiskit-ignis==0.7.0
    - qiskit-terra==0.19.1
    - requests-ntlm==1.1.0
    - retworkx==0.11.0
    - stevedore==3.5.0
    - symengine==0.8.1
    - sympy==1.9
    - tweedledum==1.1.1
    - typing-extensions==4.0.1
    - websocket-client==1.2.3
    - zipp==3.7.0
